acc_fname: acceleration.csv
init_acceleration: 0.0
init_position: 0.0
init_velocity: 0.0
model_params:
  amplitude: 5
  frequency: 3
  mass: 10
  spring: 10
pos_fname: position.csv
time_end: 15
time_step: 0.1
vel_fname: velocity.csv
